In [1]:
import requests
import dotenv
import os
dotenv.load_dotenv()  # .env 환경변수 파일을 로드함

key = os.getenv("SEOUL_API")

In [2]:
url = 'http://openapi.seoul.go.kr:8088/'+key+'/json/VwsmMegaSelngW/1/1000/'
response = requests.get(url)
print(f'접속주소 : {response.url}')
print(f'응답코드 : {response.status_code}')
result = response.json()
# 보기쉽게 들여쓰기로 출력
import json
result = result['VwsmMegaSelngW']['row']
print(len(result))
print(json.dumps(result[0],indent=4,ensure_ascii=False))

접속주소 : http://openapi.seoul.go.kr:8088/6e6f4867496a696e363768426a436c/json/VwsmMegaSelngW/1/1000/
응답코드 : 200
1000
{
    "STDR_YYQU_CD": "20243",
    "MEGA_CD": "11",
    "MEGA_CD_NM": "서울시",
    "SVC_INDUTY_CD": "CS200005",
    "SVC_INDUTY_CD_NM": "스포츠 강습",
    "THSMON_SELNG_AMT": 125621989726.0,
    "THSMON_SELNG_CO": 560552.0,
    "MDWK_SELNG_AMT": 114839751900.0,
    "WKEND_SELNG_AMT": 10782237826.0,
    "MON_SELNG_AMT": 30659656338.0,
    "TUES_SELNG_AMT": 22683014516.0,
    "WED_SELNG_AMT": 19959596104.0,
    "THUR_SELNG_AMT": 19905795231.0,
    "FRI_SELNG_AMT": 21631689711.0,
    "SAT_SELNG_AMT": 7980345220.0,
    "SUN_SELNG_AMT": 2801892606.0,
    "TMZON_00_06_SELNG_AMT": 313273700.0,
    "TMZON_06_11_SELNG_AMT": 10780496989.0,
    "TMZON_11_14_SELNG_AMT": 21717738293.0,
    "TMZON_14_17_SELNG_AMT": 27194815821.0,
    "TMZON_17_21_SELNG_AMT": 53891902018.0,
    "TMZON_21_24_SELNG_AMT": 11723762905.0,
    "ML_SELNG_AMT": 44909131421.0,
    "FML_SELNG_AMT": 76391286774.0,
    "AGRDE_10_SELNG_AMT": 264735815.0,
    "AGRDE_20_SELNG_AMT": 14179488115.0,
    "AGRDE_30_SELNG_AMT": 30537603201.0,
    "AGRDE_40_SELNG_AMT": 48808297731.0,
    "AGRDE_50_SELNG_AMT": 20404872792.0,
    "AGRDE_60_ABOVE_SELNG_AMT": 7104969583.0,
    "MDWK_SELNG_CO": 472987.0,
    "WKEND_SELNG_CO": 87565.0,
    "MON_SELNG_CO": 124015.0,
    "TUES_SELNG_CO": 90482.0,
    "WED_SELNG_CO": 86423.0,
    "THUR_SELNG_CO": 81608.0,
    "FRI_SELNG_CO": 90459.0,
    "SAT_SELNG_CO": 51815.0,
    "SUN_SELNG_CO": 35750.0,
    "TMZON_00_06_SELNG_CO": 7645.0,
    "TMZON_06_11_SELNG_CO": 48826.0,
    "TMZON_11_14_SELNG_CO": 78575.0,
    "TMZON_14_17_SELNG_CO": 135453.0,
    "TMZON_17_21_SELNG_CO": 230966.0,
    "TMZON_21_24_SELNG_CO": 59087.0,
    "ML_SELNG_CO": 248918.0,
    "FML_SELNG_CO": 300209.0,
    "AGRDE_10_SELNG_CO": 10499.0,
    "AGRDE_20_SELNG_CO": 73887.0,
    "AGRDE_30_SELNG_CO": 124032.0,
    "AGRDE_40_SELNG_CO": 237206.0,
    "AGRDE_50_SELNG_CO": 76375.0,
    "AGRDE_60_ABOVE_SELNG_CO": 27131.0
}

In [3]:
import pandas as pd
df = pd.DataFrame(result)

column_mapping = {
    "STDR_YYQU_CD": "기준_년분기_코드",
    "MEGA_CD": "서울시_코드",
    "MEGA_CD_NM": "서울시_코드_명",
    "SVC_INDUTY_CD": "서비스_업종_코드",
    "SVC_INDUTY_CD_NM": "서비스_업종_코드_명",
    "THSMON_SELNG_AMT": "당월_매출_금액",
    "THSMON_SELNG_CO": "당월_매출_건수",
    "MDWK_SELNG_AMT": "주중_매출_금액",
    "WKEND_SELNG_AMT": "주말_매출_금액",
    "MON_SELNG_AMT": "월요일_매출_금액",
    "TUES_SELNG_AMT": "화요일_매출_금액",
    "WED_SELNG_AMT": "수요일_매출_금액",
    "THUR_SELNG_AMT": "목요일_매출_금액",
    "FRI_SELNG_AMT": "금요일_매출_금액",
    "SAT_SELNG_AMT": "토요일_매출_금액",
    "SUN_SELNG_AMT": "일요일_매출_금액",
    "TMZON_00_06_SELNG_AMT": "시간대_00~06_매출_금액",
    "TMZON_06_11_SELNG_AMT": "시간대_06~11_매출_금액",
    "TMZON_11_14_SELNG_AMT": "시간대_11~14_매출_금액",
    "TMZON_14_17_SELNG_AMT": "시간대_14~17_매출_금액",
    "TMZON_17_21_SELNG_AMT": "시간대_17~21_매출_금액",
    "TMZON_21_24_SELNG_AMT": "시간대_21~24_매출_금액",
    "ML_SELNG_AMT": "남성_매출_금액",
    "FML_SELNG_AMT": "여성_매출_금액",
    "AGRDE_10_SELNG_AMT": "연령대_10_매출_금액",
    "AGRDE_20_SELNG_AMT": "연령대_20_매출_금액",
    "AGRDE_30_SELNG_AMT": "연령대_30_매출_금액",
    "AGRDE_40_SELNG_AMT": "연령대_40_매출_금액",
    "AGRDE_50_SELNG_AMT": "연령대_50_매출_금액",
    "AGRDE_60_ABOVE_SELNG_AMT": "연령대_60_이상_매출_금액",
    "MDWK_SELNG_CO": "주중_매출_건수",
    "WKEND_SELNG_CO": "주말_매출_건수",
    "MON_SELNG_CO": "월요일_매출_건수",
    "TUES_SELNG_CO": "화요일_매출_건수",
    "WED_SELNG_CO": "수요일_매출_건수",
    "THUR_SELNG_CO": "목요일_매출_건수",
    "FRI_SELNG_CO": "금요일_매출_건수",
    "SAT_SELNG_CO": "토요일_매출_건수",
    "SUN_SELNG_CO": "일요일_매출_건수",
    "TMZON_00_06_SELNG_CO": "시간대_00~06_매출_건수",
    "TMZON_06_11_SELNG_CO": "시간대_06~11_매출_건수",
    "TMZON_11_14_SELNG_CO": "시간대_11~14_매출_건수",
    "TMZON_14_17_SELNG_CO": "시간대_14~17_매출_건수",
    "TMZON_17_21_SELNG_CO": "시간대_17~21_매출_건수",
    "TMZON_21_24_SELNG_CO": "시간대_21~24_매출_건수",
    "ML_SELNG_CO": "남성_매출_건수",
    "FML_SELNG_CO": "여성_매출_건수",
    "AGRDE_10_SELNG_CO": "연령대_10_매출_건수",
    "AGRDE_20_SELNG_CO": "연령대_20_매출_건수",
    "AGRDE_30_SELNG_CO": "연령대_30_매출_건수",
    "AGRDE_40_SELNG_CO": "연령대_40_매출_건수",
    "AGRDE_50_SELNG_CO": "연령대_50_매출_건수",
    "AGRDE_60_ABOVE_SELNG_CO": "연령대_60_이상_매출_건수"
}

df.rename(columns= column_mapping, inplace=True)
df.to_csv('seoul_store.csv',index=False,encoding='cp949')

In [4]:
df.set_index('기준_년분기_코드',inplace=True)

In [5]:
df.drop(columns=['서울시_코드','서울시_코드_명','서비스_업종_코드'],inplace=True)

In [6]:
df.head()

,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,...,시간대_17~21_매출_건수,시간대_21~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
기준_년분기_코드,,,,,,,,,,,,,,,,,,,,,
20243,스포츠 강습,1.256220e+11,560552.0,1.148398e+11,1.078224e+10,3.065966e+10,2.268301e+10,1.995960e+10,1.990580e+10,2.163169e+10,...,230966.0,59087.0,248918.0,300209.0,10499.0,73887.0,124032.0,237206.0,76375.0,27131.0
20243,여관,6.684655e+10,1268476.0,4.588294e+10,2.096361e+10,9.835197e+09,8.660760e+09,8.726616e+09,9.059335e+09,9.601032e+09,...,354669.0,258571.0,869820.0,322857.0,18482.0,385561.0,328263.0,180558.0,170101.0,109699.0
20243,고시원,2.194135e+08,429.0,1.568745e+08,6.253908e+07,5.600508e+07,1.862526e+07,1.862526e+07,3.180943e+07,3.180943e+07,...,73.0,185.0,219.0,210.0,0.0,218.0,115.0,0.0,96.0,0.0
20243,편의점,1.131581e+12,165985978.0,8.347921e+11,2.967892e+11,1.723568e+11,1.594869e+11,1.626247e+11,1.650212e+11,1.753024e+11,...,42140217.0,25755768.0,100792950.0,63123710.0,3546395.0,37103083.0,46749462.0,33300287.0,28146842.0,15070636.0
20243,반찬가게,8.342301e+11,32501744.0,6.961403e+11,1.380897e+11,1.574815e+11,1.266496e+11,1.375109e+11,1.304588e+11,1.440394e+11,...,5866680.0,1246877.0,15357807.0,14937766.0,190358.0,3896771.0,7095865.0,6157793.0,6326482.0,6628285.0